version: '3.8'

services:
  watches-php:
    build: .
    container_name: watches-php
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    volumes:
      - ./index.php:/var/www/html/index.php
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro 
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
